# Initialization file for the KUKA Fast Research Interface of the Light-Weight Robot IV

[RobotName]
Name=ROB

[Priorities]
#Priority range: 1..63
KRCCommunicationThread=60
TimerThread=55
MainThread=50
OutputConsoleThread=5

[ControlValues]
# Cycle time in seconds
CycleTime=0.002

[Logging]
NumberOfLoggingFileEntries=600000
LoggingPath=C:\Users\HMMS\Documents\GitHub\Thesis\KUKA LWR\experiments\free_record
LoggingFileName=raw_log.dat